In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("D:\Data Science\Csv Files\weight-height.csv")

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\SL\AppData\Local\Temp\ipykernel_2668\2904010605.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  df = pd.read_csv("D:\Data Science\Csv Files\weight-height.csv")


In [3]:
df

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [4]:
X = df[["Height"]].values
y = df["Weight"].values

In [5]:
X

array([[73.84701702],
       [68.78190405],
       [74.11010539],
       ...,
       [63.86799221],
       [69.03424313],
       [61.94424588]], shape=(10000, 1))

In [6]:
y

array([241.89356318, 162.31047252, 212.74085556, ..., 128.47531878,
       163.85246135, 113.64910268], shape=(10000,))

In [7]:
lr_model = LinearRegression()

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [9]:
lr_model.fit(X_train, y_train)

LinearRegression()

In [10]:
# Checking Model Parameters

print("coefficent", lr_model.coef_)
print("intercept", lr_model.intercept_)

coefficent [7.70218561]
intercept -349.7878205824453


In [11]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error

## Traing Data

In [12]:
y_pred = lr_model.predict(X_train)

In [13]:
print("Mean Squared Error",mean_squared_error(y_train,y_pred))
print("r2_score" ,r2_score(y_train,y_pred))
print("mean absolute error", mean_absolute_error(y_train,y_pred))
print("root_mean_squared_error" , root_mean_squared_error(y_train,y_pred))

Mean Squared Error 149.3736986484211
r2_score 0.8545053200432668
mean absolute error 9.76071345543586
root_mean_squared_error 12.221853322979339


## Testing Data

In [14]:
y_pred = lr_model.predict(X_test)

In [15]:
print("Mean Squared Error",mean_squared_error(y_test,y_pred))
print("r2_score" ,r2_score(y_test,y_pred))
print("mean absolute error", mean_absolute_error(y_test,y_pred))
print("root_mean_squared_error" , root_mean_squared_error(y_test,y_pred))

Mean Squared Error 149.00350418448127
r2_score 0.8577317777038499
mean absolute error 9.69193380188457
root_mean_squared_error 12.206699151878908


#### Prediction of input data

In [16]:
X_test

array([[68.68723219],
       [68.82933377],
       [66.39812838],
       ...,
       [62.18893278],
       [67.06830402],
       [58.63272047]], shape=(2000, 1))

In [19]:
y_test

array([173.11581259, 195.1620421 , 170.21745116, ..., 125.17937963,
       187.57349377, 102.46908678], shape=(2000,))

In [24]:
height = float(input("Enter Height in inches"))

weight_pred = lr_model.predict([[height]])

print("Predicted Weight: ", weight_pred)

Predicted Weight:  [158.55642935]


In [25]:
import pickle

In [27]:
with open("weight_prediction.pkl", mode = "wb") as f:
    pickle.dump(lr_model,f)